### PR TITLE
feat (add-node.component) add sorting for machine types for DO

### PR DESCRIPTION
**Pull request by nikage**

### CODE REVIEW

**Comment by eldridgeh** [comment]
@nikage Can this be improved on? Thanks

**Comment by nikage** [comment]
@eldridgeh I think I'm gonna rewrite the sorting algorithm from scratch)

**Comment by josephkane** [comment]
@nikage would it be possible to sort DO machine types by their size? I know we get that information back, but I wonder how hard that would be?

**Comment by josephkane** [comment]
@nikage I'm not sure what you mean, but that prop is meant to be a reference for the resources available for each of the different machine types. Ideally in the future, we would use that information to 1. build pre-set configurations for different cluster uses (video processing, data store, etc.), and 2. display feedback on the review step (https://github.com/supergiant/control/issues/953). I had thought that using these sizes might be an easier way to sort DO machines, but it looks like you figured out a way to do it without them. Does that make sense, or did I misunderstand your question?

**Comment by eldridgeh** [comment]
@nikage 
I need to close this PR?

**Comment by nikage** [comment]
@eldridgeh approve it if you please

**Pull request merged**
